### ISSUE TITLE
symbol-links

### ISSUE THREAD

**Issue by Gleefre** [tfeb/symbol-nicknames#3]
First of all, I think it is a very interesting thing that hopefully will become a semi-standard extension at some point :).

I am wondering if you saw `symbol-links`? It seems to be almost exactly the same thing (both the idea & infect/hack mechanics).
(repo link: https://github.com/Gleefre/symbol-links)

There is also some sort of discussion on the theme that happened in this reddit thread: https://www.reddit.com/r/Common_Lisp/comments/14bxxvz/symbol_links_or_how_to_create_aliases/
One seemingly important issue would be the second value of `find-symbol`:
> I have many code which have `case` dispatching on second value of `find-symbol`, yes. All this would need to be changed. Any program which seeks to do any sophistication with symbols and packages will likely break if there are links.
> -- u/zyni-moe

One more thing - I just implemented the symbol-link hack for CMUCL and CCL, so I thought you might be interested in that too.

P.S. i didn't use discussions because I don't know what they are, sorry for any inconvenience.

**Comment by Hexstream** [comment]
As far as I can tell, the main distinguishing features of discussions are threading and voting, which is generally pretty irrelevant if there are only a few messages anyway.

**Comment by tfeb** [comment]
The problem that needs to be solved is that `(find-symbol x p)` can return a symbol whose name is one or both of

- not `string=` to `x`
- not present in `p` at all.

That can never happen in standard CL, and there needs to be a way of detecting that one or both of these cases has happened without having to encrust every call to `find-symbol` with at least two tests to detect these cases.

**Comment by tfeb** [comment]
I have no idea (and don't really care!) what github wants the distinction to be but for me

- an issue is a thing which might involve a concrete fix to the code via a PR or what have you and is then done;
- a discussion is, well, a discussion, which might give rise to one or more issues.

I am aware of symbol links: 'Zyni' is a friend of mine.  We found their interface somewhat horrid which was why symbol nicknames got invented.

Sorry if these replies are incoherent: I only have the GH app on my phone for a few days.

**Comment by Gleefre** [comment]
I see, thanks for you response. I wasn't sure if that that was the case hence my issue/question.

I suppose that symbol-links API is indeed not very great.

If you don't mind I'd like to combine these two projects as I don't see almost any difference between the two, except for symbol-nicknames being more robust [tests and such].

For that I would like to:
- put a link to symbol-nicknames in the README of my library;
- maybe implement functionality of symbol-links in terms of symbol-nicknames;
- provide CCL/CMUCL infect implementations;
- [ if you don't mind ] provide some PR's with "fixes" that might make sense, for example:
  - use trivial-garbage as portability layer for weak hash-tables
  - use implementation-specific `simple-package-error` condition where applicable (at least sbcl, cmucl, ccl).

**Comment by Hexstream** [comment]
@tfeb

> The problem that needs to be solved is that `(find-symbol x p)` can return a symbol whose name is one or both of
> 
> * not `string=` to `x`

Well, that is _almost the entire point_ of symbol nicknames, isn't it? :)

And I really can't imagine violating that assumption would break much code...

> * not present in `p` at all.
> 
> That can never happen in standard CL

Well, per standard terminology for "[present](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_p.htm#present)" (2), that can indeed happen, which is the case for `:inherited`.

But I'm assuming you really meant that the symbol named `x` is not necessarily [accessible](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_a.htm#accessible) (3) in package `p`, which doesn't make sense either, since we are clearly _accessing_ the _intended symbol_ through the _intended name_ in the _intended package_. It's almost never going to matter that the name of the symbol we are accessing _may not be the same as the name we accessed it through_, and this is an analogous situation to having a symbol accessible in a package which is not its home package.

**It's best to think of packages as sets of bindings from names to symbols**,
_in which case symbol nicknames are not confusing at all._

> and there needs to be a way of detecting that one or both of these cases has happened without having to encrust every call to `find-symbol` with at least two tests to detect these cases.

Easy! Almost all `find-symbol` callers _will never need to care_ about the distinction between symbol nicknames and "real" symbols, and for the few that do, we just need to prohibit symbol nicknames of the same name as the target symbol (_which would be confusing and useless anyway_), so if the returned symbol's name is not `string=` to the name you passed in, _then you know you have just dereferenced a symbol nickname!_

**Symbol nicknames are _shocking simple_ conceptually, don't you think?** :)

**Comment by Gleefre** [comment]
[Rather about possible extension and not this library in particular]

> The problem that needs to be solved is that (find-symbol x p) can return a symbol whose name is one or both of
>
>    not string= to x
>    not present in p at all.
>
> That can never happen in standard CL, and there needs to be a way of detecting that one or both of these cases has happened without having to encrust every call to find-symbol with at least two tests to detect these cases.

Hm, I suppose that one possible solution to this problem would be to have an additional readtable slot `readtable-use-symbol-nicknames` that controls whether the *reader* binds `*use-symbol-nicknames*` to T. With that in mind user calls to `find-symbol`/`intern` now don't need to use symbol nicknames by default. And if someone wants to explicitly use them a dynamic binding to this variable should be established around the `find-symbol`/`intern` call only.

This way existing code will not be broken; yet the possibility to use symbol-nicknames in code is not affected. (If the `readtable-use-symbol-nicknames` is set to `T` by default, otherwise you'd just need to put a single `(in-readtable ...)` line in the beginning of the file.

**Comment by Gleefre** [comment]
> if the returned symbol's name is not `string=` to the name you passed in, _then you know you have just dereferenced a symbol nickname_

The problem would be the existing codebase that **doesn't know** about symbol-nicknames (because they didn't exist), and thus **might be broken** because of such inconsistency.

**Comment by Hexstream** [comment]
The point is that **_almost 100% of code never needs to care about symbol nicknames_**...

It's a very natural extension. Or said another way:

**Common Lisp suffers from an _arbitrary limitation_, which _SCREAMS_ to be removed.**

**Comment by tfeb** [comment]
@Gleefre Sorry, I hadn't understood that symbol-links was yours: I didn't mean to be rude about it.

I'm not sure if we're at the point where there should be only one interface: symbol nicknames describes itself as 'a broken toy' and that's all it's intended to be.  In particular symbol nicknames wants to pretend there is only one symbol which has nicknames, while symbol-links is making explicit links between symbols, which is not quite the same thing.  Further I'm unconvinced that either solves a problem which would not be better solved some other way.

What I started doing before reading this thread and will publish either today or early next week is to add some contributor notes to the README and a pointer to symbol-links which should always have been there (the whole thing came about because my friend Zyni saw the symbol-links discussion on reddit and we talked about it: that should always have been referenced.

**Comment by Gleefre** [comment]
No problem :)

Hm, yes, I see the distinction now after taking a close look at symbol-nicknames; thus I won't deprecate symbol-links yet.

**Comment by Hexstream** [comment]
@tfeb Interesting revelations, but I would have thought, [given](https://github.com/tfeb/symbol-nicknames/issues/3#issuecomment-1769138129) [the](https://github.com/tfeb/symbol-nicknames/issues/3#issuecomment-1769372926) [above](https://github.com/tfeb/symbol-nicknames/issues/3#issuecomment-1769479267) and [this](https://github.com/tfeb/symbol-nicknames/discussions/2#discussioncomment-7342036), that it would be quite clear to everyone at this point that **symbol nicknames have no reason to be _broken_ nor a _toy_.**

**_symbol nickname_ simply describes a situation whereby a symbol is [accessible](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_a.htm#accessible) (3) in a package under a name different from its `symbol-name`.** _The assumption that symbols would always be accessed in packages only through their `symbol-name` had always been **superfluous and arbitrarily restrictive.**_

**edit:** I feel this should have been discovered _30+ years ago._
This is _painfully obvious_ in retrospect!

**Comment by tfeb** [comment]
I've added a pointer to symbol-links in 9e8da0c5b49c44b8e98c0fa20fe9d0a610bdea12 which I think is the only substantive change needed.

I am not going to change `find-symbol` to lie when it does something which is not compatible with the CL spec.  In particular code which merely wants to know if a symbol is accessible (sorry, was wrong to say 'present' above) in a package merely needs to check that the second value is not `nil` and has no business worrying what it is.  Code which wants to know exactly what is going on definitely needs to know that something completely nonstandard has happened.
